### ISSUE TITLE
Challenge #2: Rounding test failures

### ISSUE THREAD

**Issue by MissFacetious** [MissFacetious/codehort#22]
I expect both of these to work to rounding:

```
// this doesn't work for returning second test 53.65 instead of expected 53.67
function round(value, decimal_places) {
	return (Math.round(value*(10*decimal_places))/(10*decimal_places));
}
```

```
// this doesn't work for returning 21.00 instead of expected 21, which 21.00 is what it should be
function round(value, decimal_places) {
  	return value.toFixed(decimal_places);
}
```

....

**Comment by migliaci** [comment]
Math.round(value*(10*decimal_places))/(10*decimal_places)) isn't a valid solution.
See: console.log(Math.round(50.125*(10*2))/(10*2)); (rounding 50.125 to two decimal places).
Javascript returns 50.15 instead of 50.13.

**Comment by MissFacetious** [comment]
I expect pretty much 99% of people to use Math.round(), 
this also works
`	return Math.round(value*100)/100;	`
So perhaps the execution is the problem, need to add Math to it somehow?

**Comment by migliaci** [comment]
That one does seem to match the tests.

**Comment by migliaci** [comment]
Updated the tests. Verify at your leisure.

**Comment by MissFacetious** [comment]
value.toFixed() works but I think we need to investigate what the deal is with Math.round still
