### ISSUE TITLE
Challenge #4 Format better

### ISSUE THREAD

**Issue by MissFacetious** [MissFacetious/codehort#23]
JSON isn't lined up well.

* Array on same line as bracket }]
* two spaces instead of tabs
* nested brackets are at the same indentation as parent object -> fix

basically, keep more consistent

getLetterGrade() should be the last function because it will be the last thing to be executing other functions, for learning, it makes sense to have that be on the bottom
getWeightedNumericalGrade would probably be second?
I guess the functions should be ordered in the way you'd implement them, the tests as well.

**Comment by migliaci** [comment]
Fixed (though I use tabs and not spaces) :P
